# Generated by Django 5.2.1 on 2025-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.URLField()),
                ('offre_id', models.IntegerField()),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
