# Generated by Django 5.2.1 on 2025-05-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_candidature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidature",
            name="offre_id",
        ),
        migrations.AddField(
            model_name="candidature",
            name="offre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidatures",
                to="blog.post",
            ),
        ),
    ]
